/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'product-categories': ProductCategory;
    products: Product;
    factories: Factory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    factories: FactoriesSelect<false> | FactoriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'site-content': SiteContent;
    'page-content': PageContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
    'page-content': PageContentSelect<false> | PageContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows (style, fabric, view). Used for SEO and screen readers. Never include client or buyer brand names.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * URL slug, e.g. merchandising-support. Changing it changes the page URL.
   */
  slug: string;
  title: string;
  /**
   * lucide-react icon name, e.g. ClipboardList.
   */
  icon: string;
  summary: string;
  intro: string;
  covers: {
    item: string;
    id?: string | null;
  }[];
  how: {
    item: string;
    id?: string | null;
  }[];
  relatedCategories?: (number | ProductCategory)[] | null;
  /**
   * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
   */
  answer?: string | null;
  /**
   * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search-result overrides. Leave blank to use the automatic title and description.
   */
  seo?: {
    /**
     * Optional keyword-rich H1. Blank = the record's own title.
     */
    heading?: string | null;
    /**
     * ≤ 60 characters is ideal. Put the main keyword first.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters is ideal. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  /**
   * URL slug, e.g. knitwear. Changing it changes the page URL.
   */
  slug: string;
  title: string;
  /**
   * lucide-react icon name, e.g. Shirt.
   */
  icon: string;
  summary: string;
  intro: string;
  subItems: {
    item: string;
    id?: string | null;
  }[];
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
   */
  answer?: string | null;
  /**
   * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search-result overrides. Leave blank to use the automatic title and description.
   */
  seo?: {
    /**
     * Optional keyword-rich H1. Blank = the record's own title.
     */
    heading?: string | null;
    /**
     * ≤ 60 characters is ideal. Put the main keyword first.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters is ideal. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Running styles shown on the Products pages. Never enter client or buyer brand names.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * e.g. Men's Short-Sleeve Polo Shirt
   */
  name: string;
  /**
   * Your own style / reference number, exactly as on the spec sheet.
   */
  styleNumber?: string | null;
  category: number | ProductCategory;
  /**
   * One or two sentences shown on the product card.
   */
  summary?: string | null;
  description?: string | null;
  /**
   * e.g. 100% Pima Cotton
   */
  composition?: string | null;
  /**
   * e.g. 170 GSM
   */
  gsm?: string | null;
  /**
   * e.g. Interlock
   */
  fabricConstruction?: string | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The first photo is the main image and the card cover.
   */
  images?:
    | {
        image: number | Media;
        view?: ('front' | 'back' | 'side' | 'detail' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Generated from name + style number. Changing it changes the page URL.
   */
  slug?: string | null;
  /**
   * Show on the Home page strip.
   */
  featured?: boolean | null;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Search-result overrides. Leave blank to use the automatic title and description.
   */
  seo?: {
    /**
     * Optional keyword-rich H1. Blank = the record's own title.
     */
    heading?: string | null;
    /**
     * ≤ 60 characters is ideal. Put the main keyword first.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters is ideal. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factories".
 */
export interface Factory {
  id: number;
  /**
   * URL slug, e.g. liz-fashion. Changing it changes the page URL.
   */
  slug: string;
  name: string;
  specialty: string;
  productTypes: {
    item: string;
    id?: string | null;
  }[];
  categories?: (number | ProductCategory)[] | null;
  website?: string | null;
  logo?: (number | null) | Media;
  intro: string;
  /**
   * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
   */
  answer?: string | null;
  /**
   * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search-result overrides. Leave blank to use the automatic title and description.
   */
  seo?: {
    /**
     * Optional keyword-rich H1. Blank = the record's own title.
     */
    heading?: string | null;
    /**
     * ≤ 60 characters is ideal. Put the main keyword first.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters is ideal. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'factories';
        value: number | Factory;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  icon?: T;
  summary?: T;
  intro?: T;
  covers?:
    | T
    | {
        item?: T;
        id?: T;
      };
  how?:
    | T
    | {
        item?: T;
        id?: T;
      };
  relatedCategories?: T;
  answer?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        heading?: T;
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  icon?: T;
  summary?: T;
  intro?: T;
  subItems?:
    | T
    | {
        item?: T;
        id?: T;
      };
  image?: T;
  order?: T;
  answer?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        heading?: T;
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  styleNumber?: T;
  category?: T;
  summary?: T;
  description?: T;
  composition?: T;
  gsm?: T;
  fabricConstruction?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        view?: T;
        id?: T;
      };
  slug?: T;
  featured?: T;
  published?: T;
  order?: T;
  seo?:
    | T
    | {
        heading?: T;
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factories_select".
 */
export interface FactoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  specialty?: T;
  productTypes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  categories?: T;
  website?: T;
  logo?: T;
  intro?: T;
  answer?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        heading?: T;
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Company identity, public contact details, mission, vision and site-wide imagery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  tagline: string;
  oneLiner: string;
  domain: string;
  url: string;
  mission: string;
  vision: string;
  payment: string;
  /**
   * Shown in the footer and on the Contact page. Public inbox only — no personal addresses.
   */
  emails: {
    address: string;
    id?: string | null;
  }[];
  address: {
    line1: string;
    line2: string;
    city: string;
    country: string;
    geo: {
      lat: number;
      lng: number;
    };
  };
  /**
   * Shown in the “Who we are” sections on Home and About.
   */
  officeImage?: (number | null) | Media;
  ogImage?: (number | null) | Media;
  /**
   * Optional. Only fill in a year you can stand behind — it appears in structured data.
   */
  foundingYear?: number | null;
  /**
   * Published in llms.txt. CC BY 4.0 lets AI engines quote the site with attribution; it is a standing legal grant, so choose deliberately.
   */
  contentLicense?: ('none' | 'CC-BY-4.0') | null;
  /**
   * LinkedIn, Facebook, etc. Used as entity signals for search and AI engines.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Reusable content lists shown across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  whyChooseUs: {
    title: string;
    /**
     * lucide-react icon name, e.g. Headset.
     */
    icon: string;
    id?: string | null;
  }[];
  exportMarkets: {
    name: string;
    /**
     * ISO country code, e.g. SE, GB, US.
     */
    code: string;
    id?: string | null;
  }[];
  certifications: {
    name: string;
    full: string;
    /**
     * Optional. When present the logo is shown in the scrolling band instead of the text badge.
     */
    logo?: (number | null) | Media;
    id?: string | null;
  }[];
  qcSteps: {
    step: string;
    detail: string;
    id?: string | null;
  }[];
  productionFlow: {
    stage: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Search titles, descriptions, headings and FAQs for every main page. Blank fields use the built-in defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: number;
  home?: {
    /**
     * ≤ 60 characters. Main keyword first, brand last.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
     */
    answer?: string | null;
    /**
     * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  about?: {
    /**
     * ≤ 60 characters. Main keyword first, brand last.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
     */
    answer?: string | null;
    /**
     * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    /**
     * ≤ 60 characters. Main keyword first, brand last.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
     */
    answer?: string | null;
    /**
     * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  products?: {
    /**
     * ≤ 60 characters. Main keyword first, brand last.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
     */
    answer?: string | null;
    /**
     * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  factories?: {
    /**
     * ≤ 60 characters. Main keyword first, brand last.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
     */
    answer?: string | null;
    /**
     * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  compliance?: {
    /**
     * ≤ 60 characters. Main keyword first, brand last.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
     */
    answer?: string | null;
    /**
     * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    /**
     * ≤ 60 characters. Main keyword first, brand last.
     */
    metaTitle?: string | null;
    /**
     * ≤ 155 characters. Include the main keyword and a call to action.
     */
    metaDescription?: string | null;
    heading?: string | null;
    intro?: string | null;
    /**
     * 40–60 words of plain prose. Start with a subject–verb–object sentence that names the business once. Only facts already on the site — no superlatives, no invented numbers, no client names.
     */
    answer?: string | null;
    /**
     * Questions buyers really ask. Keep each answer factual and 40–60 words — search and AI answer engines quote these directly.
     */
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  oneLiner?: T;
  domain?: T;
  url?: T;
  mission?: T;
  vision?: T;
  payment?: T;
  emails?:
    | T
    | {
        address?: T;
        id?: T;
      };
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        country?: T;
        geo?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
      };
  officeImage?: T;
  ogImage?: T;
  foundingYear?: T;
  contentLicense?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  whyChooseUs?:
    | T
    | {
        title?: T;
        icon?: T;
        id?: T;
      };
  exportMarkets?:
    | T
    | {
        name?: T;
        code?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        full?: T;
        logo?: T;
        id?: T;
      };
  qcSteps?:
    | T
    | {
        step?: T;
        detail?: T;
        id?: T;
      };
  productionFlow?:
    | T
    | {
        stage?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content_select".
 */
export interface PageContentSelect<T extends boolean = true> {
  home?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        heading?: T;
        intro?: T;
        answer?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        heading?: T;
        intro?: T;
        answer?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        heading?: T;
        intro?: T;
        answer?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  products?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        heading?: T;
        intro?: T;
        answer?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  factories?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        heading?: T;
        intro?: T;
        answer?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  compliance?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        heading?: T;
        intro?: T;
        answer?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        heading?: T;
        intro?: T;
        answer?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}